name: Testing Action

on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Play Ansible Playbook
      uses: arillso/action.playbook@master
      with:
        playbook: ansible/deploy.yml
        inventory: ansible/inventory/ansible_hosts.yml
        private_key: ${{secrets.SSH_PRIVATE_KEY}}
        verbose: 4
