name: Testing Action

on: [push, pull_request]

jobs:
  test_action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Testing action
        uses: ./
        with:
          playbook: ansible/deploy.yml
          inventory: /ansible/inventory/ansible_hosts
          private_key: ${{secrets.SSH_PRIVATE_KEY}}
          user: shahars
        env:
          ANSIBLE_HOST_KEY_CHECKING: "false"
          ANSIBLE_DEPRECATION_WARNINGS: "false"