name: Ansible deploy

on:
  push:
    branches: [ main ]
    # Publish semver tags as releases.
  pull_request:
    branches: [ main ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible==2.9.2 requests
    - name: set ansible config secrets
      env:
        # ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
        SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
      # run: |
      #   echo "$ANSIBLE_VAULT_PASSWORD" > .ansible-vault-password
      #   mkdir .ssh
      #   echo "$DO_SSH_KEY" > .ssh/id_digitalocean
      #   chmod 600 .ssh/id_digitalocean
    - name: run exporters playbook
      run: |
        ansible-playbook -i /ansible/inventory/ansible_hosts deploy.yml -u shahars --private-key "$SSH_PRIVATE_KEY"